### ISSUE TITLE
Guide on updating code shouldn't mention 2to3

### ISSUE THREAD

**Issue by ngoldbaum** [OpenAstronomy/python-3-for-scientists#21]
2to3 is no longer the main suggestion people use to update code. Instead, people generally suggest tools like [modernize](https://pypi.org/project/modernize/) or [futurize](https://python-future.org/futurize.html). See e.g. [the CPython docs](https://docs.python.org/3/howto/pyporting.html#the-short-explanation).

**Comment by stephtdouglas** [comment]
OK, do you have time to update the text? I can do this morning it if not

**Comment by ngoldbaum** [comment]
I think I can update the text...
